Assignment 3: Data Preprocessing and EDA

Use case: Data Cleaning for E-Commerce Transactions

Online shopping platforms generate large volumes of transactional data. This data often contains duplicates, incorrect data types, and invalid values such as negative quantities or prices. Cleaning such data is a crucial preprocessing step before performing sales analysis, customer behavior analysis, or predictive modeling.

# **1. Import Libraries**

In [ ]:
import pandas as pd

# **2. Load the dataset into dataframe**

In [ ]:
df=pd.read_excel("/content/Online_Retail.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

## **3. Understand the dataset**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392692 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  object
 1   StockCode    392692 non-null  object
 2   Description  392692 non-null  object
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[ns]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  Int64
 7   Country      392692 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 27.3+ MB

Important points about data types to note here:

CustomerID is float64 → incorrect

InvoiceDate is object → should be datetime

In [ ]:
df.shape

(541909, 8)

# **4. Check the duplicates in dataset**

How duplicated() works

1. Compares entire rows

2. If all column values match a previous row → marked True

3. First occurrence = kept, rest = duplicates

How drop_duplicates() works

1. Removes rows where duplicated() == True

2. Keeps only one copy

In [ ]:
#Check the count of the duplicate rows
df.duplicated().sum()

np.int64(5268)

In [ ]:
#Remove duplicate rows
df.drop_duplicates(inplace=True)

In [ ]:
#Verify after removing duplicates
df.shape

(536641, 8)

In [ ]:
#Verify that all the duplicates are removed
df.duplicated().sum()

np.int64(0)

# **5. Fixing/ Correcting the Data Types**

**Converting InvoiceDate to DateTime**
How it works

1. Converts text → datetime object

2. errors='coerce':

Invalid dates → NaT (Not a Time)

Why needed

Enables:

1. Daily / monthly sales
2. Time-series analysis

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')

**Converting CustomerID to Integer**

In [ ]:
df['CustomerID'] = df['CustomerID'].astype('Int64')

**Fixing Quantity and UnitPrice**
How this works

1. Forces values to numeric

2. Invalid values → NaN

In [ ]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['UnitPrice'] = pd.to_numeric(df['UnitPrice'], errors='coerce')

# **6: Handling Invalid Entries**

**Removing Negative or Zero Quantity**

In [ ]:
df = df[df['Quantity'] > 0]

**Removing Zero or Negative UnitPrice**

In [ ]:
df = df[df['UnitPrice'] > 0]

# **7: Handling Missing CustomerID**
How dropna() works

Removes rows where CustomerID is NaN

subset specifies column to check

Why remove instead of filling

  CustomerID cannot be guessed

In [ ]:
df = df.dropna(subset=['CustomerID'])

# **8: Handling Missing Product Description**

In [ ]:
df['Description'] = df['Description'].fillna("Unknown Product")

# **9: Final Verification**

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 392692 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    392692 non-null  object
 1   StockCode    392692 non-null  object
 2   Description  392692 non-null  object
 3   Quantity     392692 non-null  int64
 4   InvoiceDate  392692 non-null  datetime64[ns]
 5   UnitPrice    392692 non-null  float64
 6   CustomerID   392692 non-null  Int64
 7   Country      392692 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 27.3+ MB

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

# **Summary**
1. The Online Retail e-commerce dataset was examined to identify duplicates, missing values, and inconsistent data types.

2. Duplicate records and invalid entries such as negative quantities and zero prices were removed to improve data accuracy.

3. Data types were corrected, including conversion of invoice dates and customer IDs to appropriate formats.

4. The final cleaned dataset is reliable and suitable for further analysis such as sales insights and customer analytics.