# Experiment 5: Data Wrangling on Student Performance Dataset
# Use Case: Academic Performance Analysis
# Dataset: Students Performance in Exams.csv (Open Source): https://www.kaggle.com/datasets/spscientist/students-performance-in-exams

Tasks:

- Column/row operations

- Grouping, sorting, ranking

- Merging multiple student datasets
# Outcome: Structured academic data for insights

# Aim of the Experiment
# To perform data wrangling operations such as column and row manipulation, grouping, sorting, ranking, and dataset preparation on student academic data in order to derive meaningful educational insights.

Definition

Data wrangling is the process of cleaning, transforming, structuring, and organizing raw data into a usable format so that it can be easily analyzed and interpreted.

In [ ]:
# Import Required Libraries

import pandas as pd
import numpy as np

In [ ]:
# Load the Dataset

df=pd.read_csv('/content/StudentsPerformance.csv')
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
#Renaming columns for clarity

df = df.rename(columns={
'gender': 'Gender',
'race/ethnicity': 'Ethnicity',
'parental level of education': 'Parental_Education',
'lunch': 'Lunch_Type',
'test preparation course': 'Test_Prep',
'math score': 'Math_Score',
'reading score': 'Reading_Score',
'writing score': 'Writing_Score'
})

In [ ]:
df.columns

Index(['Gender', 'Ethnicity', 'Parental_Education', 'Lunch_Type', 'Test_Prep',
       'Math_Score', 'Reading_Score', 'Writing_Score'],
      dtype='object')

In [ ]:
# Row Operations

# Students who scored more than 70 in Math
high_math = df[df['Math_Score'] > 70]
high_math

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
984,female,group C,some high school,standard,none,74,75,82
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
#Students who completed test preparation

prep_completed = df[df['Test_Prep'] == 'completed']
prep_completed

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score
1,female,group C,some college,standard,completed,69,90,88
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
13,male,group A,some college,standard,completed,78,72,70
18,male,group C,master's degree,free/reduced,completed,46,42,46
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

In [ ]:
#Feature Engineering (New Columns)

# Average score across all subjects
df['Average_Score'] = df[['Math_Score', 'Reading_Score', 'Writing_Score']].mean(axis=1)

In [ ]:
df

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score,Average_Score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667
1,female,group C,some college,standard,completed,69,90,88,82.333333
2,female,group B,master's degree,standard,none,90,95,93,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333
4,male,group C,some college,standard,none,76,78,75,76.333333
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000
998,female,group D,some college,standard,completed,68,78,77,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,83.000000

# Performance Levels Defined
Average Score	Performance Level

0 – 50	Low

50 – 75	Medium

75 – 100	High

In [ ]:
#Performance category

df['Performance_Level'] = pd.cut(df['Average_Score'],bins=[0, 50, 75, 100],labels=['Low', 'Medium', 'High'])
df

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score,Average_Score,Performance_Level
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,Medium
1,female,group C,some college,standard,completed,69,90,88,82.333333,High
2,female,group B,master's degree,standard,none,90,95,93,92.666667,High
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,Low
4,male,group C,some college,standard,none,76,78,75,76.333333,High
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,High
996,male,group C,high school,free/reduced,none,62,55,55,57.333333,Medium
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,Medium
998,female,group D,some college,standard,completed,68,78,77,74.333333,Medium
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,High

In [ ]:
#Grouping Operations

# Average score by gender

avg_by_gender = df.groupby('Gender')[['Math_Score', 'Reading_Score', 'Writing_Score']].mean()
avg_by_gender

        Math_Score  Reading_Score  Writing_Score
Gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203

In [ ]:
# Average score by lunch type

avg_by_lunch = df.groupby('Lunch_Type')['Average_Score'].mean()
avg_by_lunch

Lunch_Type
free/reduced    62.199061
standard        70.837209
Name: Average_Score, dtype: float64

In [ ]:
#Sorting and Ranking

#  Sorting students by average score
sorted_df = df.sort_values(by='Average_Score', ascending=False)
sorted_df

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score,Average_Score,Performance_Level
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000,High
962,female,group E,associate's degree,standard,none,100,100,100,100.000000,High
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000,High
114,female,group E,bachelor's degree,standard,completed,99,100,100,99.666667,High
712,female,group D,some college,standard,none,98,100,99,99.000000,High
...,...,...,...,...,...,...,...,...,...,...
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000,Low
327,male,group A,some college,free/reduced,none,28,23,19,23.333333,Low
596,male,group B,high school,free/reduced,none,30,24,15,23.000000,Low
980,female,group B,high school,free/reduced,none,8,24,23,18.333333,Low
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000,Low

In [ ]:
# Ranking students based on average score

sorted_df['Rank'] = sorted_df['Average_Score'].rank(method='dense', ascending=False)

sorted_df.head()

# method='dense': Students with the same score get the same rank

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score,Average_Score,Performance_Level,Rank
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000,High,1.0
962,female,group E,associate's degree,standard,none,100,100,100,100.000000,High,1.0
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000,High,1.0
114,female,group E,bachelor's degree,standard,completed,99,100,100,99.666667,High,2.0
712,female,group D,some college,standard,none,98,100,99,99.000000,High,3.0

In [ ]:
#Merging Multiple Student Datasets (Simulation)

# Creating a second dataset containing attendance information

attendance_df = df[['Gender']].copy()
attendance_df['Attendance_Percentage'] = np.random.randint(60, 100, size=len(attendance_df))
attendance_df

     Gender  Attendance_Percentage
0    female                     68
1    female                     97
2    female                     72
3      male                     89
4      male                     65
..      ...                    ...
995  female                     90
996    male                     72
997  female                     92
998  female                     65
999  female                     89

[1000 rows x 2 columns]

In [ ]:
# Merging academic performance with attendance data

merged_df = pd.concat([df, attendance_df['Attendance_Percentage']], axis=1)
merged_df

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score,Average_Score,Performance_Level,Attendance_Percentage
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,Medium,68
1,female,group C,some college,standard,completed,69,90,88,82.333333,High,97
2,female,group B,master's degree,standard,none,90,95,93,92.666667,High,72
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,Low,89
4,male,group C,some college,standard,none,76,78,75,76.333333,High,65
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,High,90
996,male,group C,high school,free/reduced,none,62,55,55,57.333333,Medium,72
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,Medium,92
998,female,group D,some college,standard,completed,68,78,77,74.333333,Medium,65
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,High,89

In [ ]:
# Insights from Merged Dataset

# Relationship between attendance and average score
high_attendance = merged_df[merged_df['Attendance_Percentage'] > 85]
high_attendance

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score,Average_Score,Performance_Level,Attendance_Percentage
1,female,group C,some college,standard,completed,69,90,88,82.333333,High,97
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,Low,89
5,female,group B,associate's degree,standard,none,71,83,78,77.333333,High,96
8,male,group D,high school,free/reduced,completed,64,64,67,65.000000,Medium,93
10,male,group C,associate's degree,standard,none,58,54,52,54.666667,Medium,93
...,...,...,...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74,69.333333,Medium,99
994,male,group A,high school,standard,none,63,63,62,62.666667,Medium,90
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,High,90
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,Medium,92
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,High,89

In [ ]:
merged_df

,Gender,Ethnicity,Parental_Education,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score,Average_Score,Performance_Level,Attendance_Percentage
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667,Medium,68
1,female,group C,some college,standard,completed,69,90,88,82.333333,High,97
2,female,group B,master's degree,standard,none,90,95,93,92.666667,High,72
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.333333,Low,89
4,male,group C,some college,standard,none,76,78,75,76.333333,High,65
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.000000,High,90
996,male,group C,high school,free/reduced,none,62,55,55,57.333333,Medium,72
997,female,group C,high school,free/reduced,completed,59,71,65,65.000000,Medium,92
998,female,group D,some college,standard,completed,68,78,77,74.333333,Medium,65
999,female,group D,some college,free/reduced,none,77,86,86,83.000000,High,89

In [ ]:
#Final Structured Dataset

final_df = merged_df[['Gender', 'Lunch_Type', 'Test_Prep',
'Math_Score', 'Reading_Score', 'Writing_Score',
'Average_Score', 'Performance_Level', 'Attendance_Percentage']]

final_df

,Gender,Lunch_Type,Test_Prep,Math_Score,Reading_Score,Writing_Score,Average_Score,Performance_Level,Attendance_Percentage
0,female,standard,none,72,72,74,72.666667,Medium,68
1,female,standard,completed,69,90,88,82.333333,High,97
2,female,standard,none,90,95,93,92.666667,High,72
3,male,free/reduced,none,47,57,44,49.333333,Low,89
4,male,standard,none,76,78,75,76.333333,High,65
...,...,...,...,...,...,...,...,...,...
995,female,standard,completed,88,99,95,94.000000,High,90
996,male,free/reduced,none,62,55,55,57.333333,Medium,72
997,female,free/reduced,completed,59,71,65,65.000000,Medium,92
998,female,standard,completed,68,78,77,74.333333,Medium,65
999,female,free/reduced,none,77,86,86,83.000000,High,89

In [ ]:
final_df.to_csv('structured_student_performance.csv', index=False)